### PR TITLE
added basic styling

### PR DESCRIPTION
**Pull request by Kswierk**
Is that what you expected ?

### CODE REVIEW

**Comment by jacobhamilton12** [comment]
Looks pretty good to me

**Comment by jacobhamilton12** [comment]
I will leave the issue open as there are still a few things that can be done like the error message for example. But thanks for helping

**Comment by jacobhamilton12** [comment]
I actually reverted it because the table is off to the left after loading it

**Comment by Kswierk** [comment]
Can you please tell me what should I type in imputs to display the table? I will fix it for sure

**Comment by jacobhamilton12** [comment]
Yeah the table doesn't actually exist on the page until a valid query is submitted (see updated readme for a search you can do). However styles still work for future elements. At the bottom of index.js you will see the table written as a string. Using the id's in the string you can write normal css.

**Pull request merged**
